// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (c) 2017-2020, Linaro Limited
 */

#include <ck_debug.h>
#include <pkcs11_ta.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "local_utils.h"

#define CK2STR_ENTRY(id)	case id: return #id

/*
 * ckr2str - Return a pointer to a string buffer of "CKR_xxx\0" return value ID
 */
const char *ckr2str(CK_RV id)
{
	switch (id) {
	CK2STR_ENTRY(CKR_OK);
	CK2STR_ENTRY(CKR_CANCEL);
	CK2STR_ENTRY(CKR_HOST_MEMORY);
	CK2STR_ENTRY(CKR_SLOT_ID_INVALID);
	CK2STR_ENTRY(CKR_GENERAL_ERROR);
	CK2STR_ENTRY(CKR_FUNCTION_FAILED);
	CK2STR_ENTRY(CKR_ARGUMENTS_BAD);
	CK2STR_ENTRY(CKR_NO_EVENT);
	CK2STR_ENTRY(CKR_NEED_TO_CREATE_THREADS);
	CK2STR_ENTRY(CKR_CANT_LOCK);
	CK2STR_ENTRY(CKR_ATTRIBUTE_READ_ONLY);
	CK2STR_ENTRY(CKR_ATTRIBUTE_SENSITIVE);
	CK2STR_ENTRY(CKR_ATTRIBUTE_TYPE_INVALID);
	CK2STR_ENTRY(CKR_ATTRIBUTE_VALUE_INVALID);
	CK2STR_ENTRY(CKR_ACTION_PROHIBITED);
	CK2STR_ENTRY(CKR_DATA_INVALID);
	CK2STR_ENTRY(CKR_DATA_LEN_RANGE);
	CK2STR_ENTRY(CKR_DEVICE_ERROR);
	CK2STR_ENTRY(CKR_DEVICE_MEMORY);
	CK2STR_ENTRY(CKR_DEVICE_REMOVED);
	CK2STR_ENTRY(CKR_ENCRYPTED_DATA_INVALID);
	CK2STR_ENTRY(CKR_ENCRYPTED_DATA_LEN_RANGE);
	CK2STR_ENTRY(CKR_FUNCTION_CANCELED);
	CK2STR_ENTRY(CKR_FUNCTION_NOT_PARALLEL);
	CK2STR_ENTRY(CKR_FUNCTION_NOT_SUPPORTED);
	CK2STR_ENTRY(CKR_KEY_HANDLE_INVALID);
	CK2STR_ENTRY(CKR_KEY_SIZE_RANGE);
	CK2STR_ENTRY(CKR_KEY_TYPE_INCONSISTENT);
	CK2STR_ENTRY(CKR_KEY_NOT_NEEDED);
	CK2STR_ENTRY(CKR_KEY_CHANGED);
	CK2STR_ENTRY(CKR_KEY_NEEDED);
	CK2STR_ENTRY(CKR_KEY_INDIGESTIBLE);
	CK2STR_ENTRY(CKR_KEY_FUNCTION_NOT_PERMITTED);
	CK2STR_ENTRY(CKR_KEY_NOT_WRAPPABLE);
	CK2STR_ENTRY(CKR_KEY_UNEXTRACTABLE);
	CK2STR_ENTRY(CKR_MECHANISM_INVALID);
	CK2STR_ENTRY(CKR_MECHANISM_PARAM_INVALID);
	CK2STR_ENTRY(CKR_OBJECT_HANDLE_INVALID);
	CK2STR_ENTRY(CKR_OPERATION_ACTIVE);
	CK2STR_ENTRY(CKR_OPERATION_NOT_INITIALIZED);
	CK2STR_ENTRY(CKR_PIN_INCORRECT);
	CK2STR_ENTRY(CKR_PIN_INVALID);
	CK2STR_ENTRY(CKR_PIN_LEN_RANGE);
	CK2STR_ENTRY(CKR_PIN_EXPIRED);
	CK2STR_ENTRY(CKR_PIN_LOCKED);
	CK2STR_ENTRY(CKR_SESSION_CLOSED);
	CK2STR_ENTRY(CKR_SESSION_COUNT);
	CK2STR_ENTRY(CKR_SESSION_HANDLE_INVALID);
	CK2STR_ENTRY(CKR_SESSION_PARALLEL_NOT_SUPPORTED);
	CK2STR_ENTRY(CKR_SESSION_READ_ONLY);
	CK2STR_ENTRY(CKR_SESSION_EXISTS);
	CK2STR_ENTRY(CKR_SESSION_READ_ONLY_EXISTS);
	CK2STR_ENTRY(CKR_SESSION_READ_WRITE_SO_EXISTS);
	CK2STR_ENTRY(CKR_SIGNATURE_INVALID);
	CK2STR_ENTRY(CKR_SIGNATURE_LEN_RANGE);
	CK2STR_ENTRY(CKR_TEMPLATE_INCOMPLETE);
	CK2STR_ENTRY(CKR_TEMPLATE_INCONSISTENT);
	CK2STR_ENTRY(CKR_TOKEN_NOT_PRESENT);
	CK2STR_ENTRY(CKR_TOKEN_NOT_RECOGNIZED);
	CK2STR_ENTRY(CKR_TOKEN_WRITE_PROTECTED);
	CK2STR_ENTRY(CKR_UNWRAPPING_KEY_HANDLE_INVALID);
	CK2STR_ENTRY(CKR_UNWRAPPING_KEY_SIZE_RANGE);
	CK2STR_ENTRY(CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT);
	CK2STR_ENTRY(CKR_USER_ALREADY_LOGGED_IN);
	CK2STR_ENTRY(CKR_USER_NOT_LOGGED_IN);
	CK2STR_ENTRY(CKR_USER_PIN_NOT_INITIALIZED);
	CK2STR_ENTRY(CKR_USER_TYPE_INVALID);
	CK2STR_ENTRY(CKR_USER_ANOTHER_ALREADY_LOGGED_IN);
	CK2STR_ENTRY(CKR_USER_TOO_MANY_TYPES);
	CK2STR_ENTRY(CKR_WRAPPED_KEY_INVALID);
	CK2STR_ENTRY(CKR_WRAPPED_KEY_LEN_RANGE);
	CK2STR_ENTRY(CKR_WRAPPING_KEY_HANDLE_INVALID);
	CK2STR_ENTRY(CKR_WRAPPING_KEY_SIZE_RANGE);
	CK2STR_ENTRY(CKR_WRAPPING_KEY_TYPE_INCONSISTENT);
	CK2STR_ENTRY(CKR_RANDOM_SEED_NOT_SUPPORTED);
	CK2STR_ENTRY(CKR_RANDOM_NO_RNG);
	CK2STR_ENTRY(CKR_DOMAIN_PARAMS_INVALID);
	CK2STR_ENTRY(CKR_CURVE_NOT_SUPPORTED);
	CK2STR_ENTRY(CKR_BUFFER_TOO_SMALL);
	CK2STR_ENTRY(CKR_SAVED_STATE_INVALID);
	CK2STR_ENTRY(CKR_INFORMATION_SENSITIVE);
	CK2STR_ENTRY(CKR_STATE_UNSAVEABLE);
	CK2STR_ENTRY(CKR_CRYPTOKI_NOT_INITIALIZED);
	CK2STR_ENTRY(CKR_CRYPTOKI_ALREADY_INITIALIZED);
	CK2STR_ENTRY(CKR_MUTEX_BAD);
	CK2STR_ENTRY(CKR_MUTEX_NOT_LOCKED);
	CK2STR_ENTRY(CKR_NEW_PIN_MODE);
	CK2STR_ENTRY(CKR_NEXT_OTP);
	CK2STR_ENTRY(CKR_EXCEEDED_MAX_ITERATIONS);
	CK2STR_ENTRY(CKR_FIPS_SELF_TEST_FAILED);
	CK2STR_ENTRY(CKR_LIBRARY_LOAD_FAILED);
	CK2STR_ENTRY(CKR_PIN_TOO_WEAK);
	CK2STR_ENTRY(CKR_PUBLIC_KEY_INVALID);
	CK2STR_ENTRY(CKR_FUNCTION_REJECTED);
	default:
		if (id & CKR_VENDOR_DEFINED)
			return "Vendor defined";
		else
			return "Unknown ID";
	}
}
